baseURL: https://wiki.openincubator.tech
languageCode: fr-fr
title: Open Ressources
theme: book

params:
  BookMenuBundle: /menu
  BookRepo: https://github.com/open-incubator/wiki
  BookEditPath:  edit/master/content
