version: '3'

services:
  hugo:
    build: .
    networks:
      - proxy
    ports:
      - 1313:1313
    labels:
      - traefik.frontend.rule=Host:wiki.openincubator.tech
      - traefik.port=1313

networks:
   proxy:
     external:
       name: "traefik-net"
