name: Build Site

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Build Site
        uses: chabad360/hugo-actions@master
      - name: Publish Site
        uses: chabad360/hugo-actions@master
        with:
          buildPath: 'public'
          # Use if you have a need to build the site to another directory
          args: -D --minify
          # Use if you want to pass some custom arguments to Hugo        
