# This is a basic workflow to help you get started with Actions

name: Github Pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/hugo-build-action@master
      with:
        args: --minify --buildDrafts
    - uses: actions/upload-artifact@master
      with:
        name: website
        path: './public'
        echo test, and deploy your project.
